### ISSUE TITLE
ImportError: cannot import name 'StrSerializer'

### ISSUE THREAD

**Issue by yuriescl** [NicolasLM/bplustree#2]
After installing `bplustree` using pip (`pip install --user bplustree`), I get the following error when importing the class StrSerializer:

```shell
  from bplustree import BPlusTree, StrSerializer
ImportError: cannot import name 'StrSerializer'
```

The error does not occur when I install `bplustree` using `python3 setup.py install --user`.

**Comment by NicolasLM** [comment]
This is because the version on PyPI (`0.0.1`) is far behind master. I will upload a new release.

**Comment by NicolasLM** [comment]
Hey @yuriescl, a new version has been released on PyPI.
