### ISSUE TITLE
Is there some problem with the write_to_file method?

### ISSUE THREAD

**Issue by bwangel23** [NicolasLM/bplustree#4]
The [`write_to_file` method](https://github.com/NicolasLM/bplustree/blob/23c2ed3b2fc3c43f2520772b8088a5592c810a02/bplustree/memory.py#L52-L59) is as follows:

```py
def write_to_file(file_fd: io.FileIO, dir_fileno: Optional[int],
                  data: bytes, fsync: bool=True):
    length_to_write = len(data)
    written = 0
    while written < length_to_write:
        written = file_fd.write(data[written:])
    if fsync:
        fsync_file_and_dir(file_fd.fileno(), dir_fileno)
```

I think the line 6 `written = file_fd.write(data[written:])` should be changed to `written += file_fd.write(data[written:])`. If not, it will enter an endless loop.

At last, I write a unittest for `write_to_file` by mock the `file_fd.write`, as shown below:

```py
def test_write_to_file():
    def side_effect(*args, **kwargs):
        if len(args) == 1:
            data = args[0]
        if len(data) > 5:
            return 5
        else:
            return len(data)

    mock_fd = mock.MagicMock()
    mock_fd.write.side_effect = side_effect

    write_to_file(mock_fd, None, b'abcdefg')
```

**Comment by NicolasLM** [comment]
You're right! Would you like to send a pull request?
