### ISSUE TITLE
DeprecationWarning: generator 'BPlusTree._iter_slice' raised StopIteration

### ISSUE THREAD

**Issue by xplorld** [NicolasLM/bplustree#7]
```
/usr/local/lib/python3.6/site-packages/bplustree/tree.py:236: DeprecationWarning: generator 'BPlusTree._iter_slice' raised StopIteration
  for record in self._iter_slice(slice_):
```

In tree.py:303, we use `raise StopIteration()` to mark termination of the generator. It is now deprecated in Python 3.5 by [PEP 479](https://www.python.org/dev/peps/pep-0479/). Please use `return` instead, if you would like to work solely above 3.5.

**Comment by NicolasLM** [comment]
Thank you very much for the advice. The fix is on master.
