### ISSUE TITLE
a little thing but not bug in the code

### ISSUE THREAD

**Issue by alwaysused** [NicolasLM/bplustree#8]
Hi.I've been learning bplusTree recently and I found your code which has been great help for me.Thank you. But I met some problem  today in  the Node's dump() function。I list some lines below.
1     data = (
2           used_key_length.to_bytes(USED_VALUE_LENGTH_BYTES, ENDIAN) +
3          key_as_bytes +
4            bytes(self._tree_conf.key_size - used_key_length) +
5           used_value_length.to_bytes(USED_VALUE_LENGTH_BYTES, ENDIAN) +
6            value +
7            bytes(self._tree_conf.value_size - used_value_length) +
 8           overflow_page.to_bytes(PAGE_REFERENCE_BYTES, ENDIAN)
 9       )
you see, the to_bytes() has pointed out the length for representing the int(key_as_bytes), which means whatever the key is , it will cost fixed bytes(USED_VALUE_LENGTH_BYTES = 8), so i wonder that if  the  variant-> used_key_length is necessary or not. Maybe this is about overflow? i'm not sure about that.Hope for you reply : ）thank you.

**Comment by NicolasLM** [comment]
It is true that whatever the actual size of the key is, it will end up using the same amount of space once on disk. But later when calling `load` it is important to know how much of this space is actually useful data (and not just filled with zeros).

I am closing this issue, but feel free to comment is something is not clear in my explanation.
